name: easiest_remote_localization
description: "Remote localization providers for the Easiest Localization Package"
version: 1.0.0
repository: https://github.com/alphamikle/easiest_remote_localization

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.5.0+1
  json_annotation: ^4.9.0
  yaml: ^3.1.2
  shared_preferences: ^2.3.1
  easiest_localization:
    path: ../locy

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter: